variables:
  INSTALL_DIR: "/usr/bin/led_strip"

run:
  stage: deploy
  environment:
    name: production
  script:
    # Print out python version for debugging
    - python -V
    # Install dependencies in case they are not yet installed.
    # numpy is installed using aptitude, as it times out using pip
    - apt-get install python-pip python3-numpy -y
    # First try to load the current venv, otherwise install a new one
    - (source $INSTALL_DIR/venv/bin/activate)
      || (pip install virtualenv && virtualenv $INSTALL_DIR/venv && source $INSTALL_DIR/venv/bin/activate)
    # Install all dependencies
    - pip install -r requirements-prod.txt -r requirements.txt
    # Copy the source code
    - sudo cp -r . $INSTALL_DIR
    # Update the service
    - |
        sudo echo "
            [Unit]
            Description=LED Strip Service
            After=multi-user.target
            Conflicts=getty@tty1.service

            [Service]
            Type=simple
            Restart=on-failure
            ExecStart=/usr/bin/led_strip/venv/bin/python $INSTALL_DIR/src/led_strip.py
            StandardInput=tty-force

            [Install]
            WantedBy=multi-user.target" > /lib/systemd/system/led_strip.service
    # Reload the daemon and restart
    - sudo systemctl daemon-reload
    - sudo systemctl restart led_strip
    - systemctl is-active --quiet led_strip
  tags:
    - production
