variables:
  INSTALL_DIR: "/usr/bin/led_strip"

run:
  stage: deploy
  environment:
    name: production
  script:
    # Install dependencies in case they are not yet installed.
    # numpy is installed using aptitude, as it times out using pip
    - apt-get install python3 python3-pip -y
    # Print out python version for debugging
    - python3 -V
    # First try to load the current venv, otherwise install a new one
    - ($INSTALL_DIR/venv/bin/python3 -m pip install -r requirements-prod.txt -r requirements.txt)
      || (pip3 install virtualenv && virtualenv -p python3 $INSTALL_DIR/venv && $INSTALL_DIR/venv/bin/python3 -m pip install -r requirements-prod.txt -r requirements.txt)
    # Copy the source code
    - sudo cp -r . $INSTALL_DIR
    # Update the service
    - |
        sudo echo "
            [Unit]
            Description=LED Strip Service
            After=multi-user.target
            Conflicts=getty@tty1.service

            [Service]
            Type=simple
            Restart=on-failure
            ExecStart=/usr/bin/led_strip/venv/bin/python3 $INSTALL_DIR/src/cli.py
            StandardInput=tty-force

            [Install]
            WantedBy=multi-user.target" > /lib/systemd/system/led_strip.service
    # Reload the daemon and restart
    - sudo systemctl daemon-reload
    - sudo systemctl restart led_strip
    # Check if the service didn't exit immediately
    - systemctl is-active --quiet led_strip
  only:
    - master
  tags:
    - production
